"""Tests for security features of the sandbox shim system.

Covers auth token generation, handshake validation, WM_ message allowlisting,
frame size limits, and .wsb security configuration.
"""

from __future__ import annotations

import secrets
import struct
import xml.etree.ElementTree as ET
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from src.sandbox.ipc.protocol import (
    FrameTooLargeError,
    MAX_FRAME_SIZE,
    MSG_AUTH,
    MSG_AUTH_FAIL,
    MSG_AUTH_OK,
    encode_frame,
    make_auth,
)
from src.sandbox.lifecycle.sandbox_manager import SandboxLifecycleManager


class TestAuthToken:
    """Tests for authentication token generation and validation."""

    def test_auth_token_length(self) -> None:
        """Token is 64 hex characters (256 bits)."""
        token = secrets.token_hex(32)
        assert len(token) == 64
        # Verify it's valid hex
        int(token, 16)

    @patch("subprocess.Popen")
    @patch("src.sandbox.ipc.shim_ipc_client.ShimIPCClient.discover_port", return_value=9876)
    def test_auth_token_length_from_manager(
        self, mock_port: MagicMock, mock_popen: MagicMock, tmp_path: Path
    ) -> None:
        """Token generated by the manager during start is 64 hex characters."""
        dll_folder = tmp_path / "dlls"
        dll_folder.mkdir()
        (dll_folder / "shim64.dll").write_bytes(b"fake")

        mock_proc = MagicMock()
        mock_proc.poll.return_value = None
        mock_proc.pid = 3000
        mock_popen.return_value = mock_proc

        mgr = SandboxLifecycleManager(dll_folder=dll_folder)
        mgr.start(exe_path="C:\\test.exe", timeout=5.0)
        assert len(mgr._token) == 64
        int(mgr._token, 16)
        mgr.stop()


class TestAuthHandshake:
    """Tests for authentication handshake logic."""

    def test_auth_handshake_success(self) -> None:
        """Correct token accepted."""
        expected_token = secrets.token_hex(32)
        auth_frame = make_auth(expected_token)

        # Simulate server-side validation
        assert auth_frame["type"] == MSG_AUTH
        assert auth_frame["token"] == expected_token

        # Server would compare tokens
        incoming_token = auth_frame["token"]
        assert incoming_token == expected_token  # -> auth_ok

    def test_auth_handshake_wrong_token(self) -> None:
        """Wrong token rejected."""
        server_token = secrets.token_hex(32)
        client_token = secrets.token_hex(32)

        # Ensure they're different (astronomically unlikely to collide)
        assert server_token != client_token

        auth_frame = make_auth(client_token)
        incoming_token = auth_frame["token"]

        # Server-side comparison fails
        assert incoming_token != server_token  # -> auth_fail


class TestWmAllowlist:
    """Tests for WM_ message allowlisting.

    The shim DLL should only inject specific window messages.
    Dangerous messages (WM_CLOSE, WM_QUIT, etc.) must be blocked.
    """

    # Expected allowlist based on shim requirements
    WM_ALLOWED = frozenset({
        0x0100,  # WM_KEYDOWN
        0x0101,  # WM_KEYUP
        0x0102,  # WM_CHAR
        0x0200,  # WM_MOUSEMOVE
        0x0201,  # WM_LBUTTONDOWN
        0x0202,  # WM_LBUTTONUP
        0x0204,  # WM_RBUTTONDOWN
        0x0205,  # WM_RBUTTONUP
        0x020A,  # WM_MOUSEWHEEL
    })

    WM_BLOCKED = frozenset({
        0x0010,  # WM_CLOSE
        0x0012,  # WM_QUIT
        0x0002,  # WM_DESTROY
        0x0050,  # WM_INPUTLANGCHANGEREQUEST
    })

    def test_wm_allowlist_accepted(self) -> None:
        """Allowed WM_ messages pass through (disjoint from blocked set)."""
        for wm_msg in self.WM_ALLOWED:
            assert wm_msg not in self.WM_BLOCKED
            assert wm_msg in self.WM_ALLOWED

    def test_wm_allowlist_rejected(self) -> None:
        """WM_CLOSE, WM_QUIT rejected (not in allowed set)."""
        for wm_msg in self.WM_BLOCKED:
            assert wm_msg not in self.WM_ALLOWED


class TestFrameSizeLimit:
    """Tests for frame size enforcement."""

    def test_frame_size_limit(self) -> None:
        """>16MB frame rejected with FrameTooLargeError."""
        huge_data = {"payload": "x" * (MAX_FRAME_SIZE + 1)}
        with pytest.raises(FrameTooLargeError):
            encode_frame(huge_data)

    def test_frame_at_limit_succeeds(self) -> None:
        """Frame under the limit should succeed."""
        near_limit_data = {"d": "x" * (MAX_FRAME_SIZE - 100)}
        raw = encode_frame(near_limit_data)
        assert len(raw) > 0

    def test_frame_size_zero(self) -> None:
        """Empty dict encodes to small frame."""
        raw = encode_frame({})
        # Empty JSON object {} = 2 bytes, plus 4-byte header = 6 bytes
        assert len(raw) == 6


class TestWsbSecurityConfig:
    """Tests for .wsb file security settings."""

    @patch("subprocess.Popen")
    @patch("src.sandbox.ipc.shim_ipc_client.ShimIPCClient.discover_port", return_value=9876)
    def test_wsb_clipboard_disabled(
        self, mock_port: MagicMock, mock_popen: MagicMock, tmp_path: Path
    ) -> None:
        """.wsb has ClipboardRedirection=Disable."""
        dll_folder = tmp_path / "dlls"
        dll_folder.mkdir()
        (dll_folder / "shim64.dll").write_bytes(b"fake")

        mock_proc = MagicMock()
        mock_proc.poll.return_value = None
        mock_proc.pid = 3001
        mock_popen.return_value = mock_proc

        mgr = SandboxLifecycleManager(dll_folder=dll_folder)
        mgr.start(exe_path="C:\\test.exe", timeout=5.0)

        tree = ET.parse(mgr._wsb_path)
        clip = tree.getroot().find("ClipboardRedirection")
        assert clip is not None
        assert clip.text == "Disable"
        mgr.stop()

    @patch("subprocess.Popen")
    @patch("src.sandbox.ipc.shim_ipc_client.ShimIPCClient.discover_port", return_value=9876)
    def test_wsb_vgpu_disabled(
        self, mock_port: MagicMock, mock_popen: MagicMock, tmp_path: Path
    ) -> None:
        """.wsb has VGpu=Disable."""
        dll_folder = tmp_path / "dlls"
        dll_folder.mkdir()
        (dll_folder / "shim64.dll").write_bytes(b"fake")

        mock_proc = MagicMock()
        mock_proc.poll.return_value = None
        mock_proc.pid = 3002
        mock_popen.return_value = mock_proc

        mgr = SandboxLifecycleManager(dll_folder=dll_folder)
        mgr.start(exe_path="C:\\test.exe", timeout=5.0)

        tree = ET.parse(mgr._wsb_path)
        vgpu = tree.getroot().find("VGpu")
        assert vgpu is not None
        assert vgpu.text == "Disable"
        mgr.stop()
